"use client";

import { useEffect, useState } from "react";
import {
  listReports,
  generateReport,
  listExperiments,
  exportReport,
  type Report,
  type Experiment,
} from "@/lib/api";
import { Button, Card, EmptyState } from "@/components/ui";

export function ReportsTab({
  projectId,
  onChange,
}: {
  projectId: string;
  onChange: () => void;
}) {
  const [reports, setReports] = useState<Report[]>([]);
  const [experiments, setExperiments] = useState<Experiment[]>([]);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [title, setTitle] = useState("");
  const [busy, setBusy] = useState(false);
  const [open, setOpen] = useState<string | null>(null);
  const [exporting, setExporting] = useState<string | null>(null);
  const [exportErr, setExportErr] = useState("");

  async function handleExport(r: Report) {
    setExporting(r.id);
    setExportErr("");
    try {
      await exportReport(r.id, r.title);
    } catch {
      setExportErr("导出失败，请重试");
    } finally {
      setExporting(null);
    }
  }

  async function refresh() {
    const [r, e] = await Promise.all([
      listReports(projectId),
      listExperiments(projectId),
    ]);
    setReports(r);
    setExperiments(e.filter((x) => x.status === "completed"));
  }
  useEffect(() => {
    refresh();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId]);

  function toggle(id: string) {
    setSelected((s) => {
      const n = new Set(s);
      if (n.has(id)) n.delete(id);
      else n.add(id);
      return n;
    });
  }

  async function handleGenerate() {
    if (selected.size === 0) return;
    setBusy(true);
    try {
      await generateReport({
        project_id: projectId,
        experiment_ids: [...selected],
        title: title || undefined,
      });
      setSelected(new Set());
      setTitle("");
      refresh();
      onChange();
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="space-y-4">
      <Card className="p-4">
        <p className="mb-3 text-sm font-medium text-slate-700">
          基于已完成的实验生成 AI 报告
        </p>
        {experiments.length === 0 ? (
          <p className="text-sm text-slate-400">
            暂无已完成的实验。请先运行一些实验。
          </p>
        ) : (
          <>
            <div className="mb-3 space-y-1">
              {experiments.map((e) => (
                <label key={e.id} className="flex items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={selected.has(e.id)}
                    onChange={() => toggle(e.id)}
                  />
                  {e.name}{" "}
                  <span className="text-xs text-slate-400">
                    acc {(Number(e.metrics.accuracy) * 100).toFixed(1)}%
                  </span>
                </label>
              ))}
            </div>
            <div className="flex items-end gap-3">
              <input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="报告标题(可选)"
                className="flex-1 rounded-md border border-slate-300 px-3 py-1.5 text-sm"
              />
              <Button onClick={handleGenerate} disabled={busy || selected.size === 0}>
                {busy ? "生成中…" : "生成报告"}
              </Button>
            </div>
          </>
        )}
      </Card>

      {reports.length === 0 ? (
        <EmptyState message="暂无报告。" />
      ) : (
        <div className="space-y-2">
          {reports.map((r) => (
            <Card key={r.id} className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">{r.title}</p>
                  <p className="text-xs text-slate-500">
                    {r.experiment_ids.length} experiment(s) · generated by{" "}
                    <span className="font-mono">{r.generated_by}</span>
                  </p>
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="secondary"
                    onClick={() => setOpen(open === r.id ? null : r.id)}
                  >
                    {open === r.id ? "收起" : "查看"}
                  </Button>
                  <Button
                    variant="ghost"
                    onClick={() => handleExport(r)}
                    disabled={exporting === r.id}
                  >
                    {exporting === r.id ? "导出中…" : "导出 .md"}
                  </Button>
                </div>
                {exportErr && (
                  <p className="mt-2 text-xs text-red-600">{exportErr}</p>
                )}
              </div>
              {open === r.id && (
                <pre className="mt-3 max-h-[500px] overflow-auto whitespace-pre-wrap rounded-md border border-slate-200 bg-slate-50 p-4 text-xs leading-relaxed text-slate-700">
                  {r.content_markdown}
                </pre>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
